import type { Metadata } from "next";
import { Inter, Special_Elite } from "next/font/google";
import LocalFont from "next/font/local";
import "@/styles/globals.css";

// 영문 폰트
const getInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// 국문 폰트
const getPretendard = LocalFont({
  src: [
    { path: "../public/fonts/Pretendard/Pretendard-Thin.woff2", weight: "100" },
    {
      path: "../public/fonts/Pretendard/Pretendard-ExtraLight.woff2",
      weight: "200",
    },
    {
      path: "../public/fonts/Pretendard/Pretendard-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/Pretendard/Pretendard-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Pretendard/Pretendard-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/Pretendard/Pretendard-SemiBold.woff2",
      weight: "600",
    },
    { path: "../public/fonts/Pretendard/Pretendard-Bold.woff2", weight: "700" },
    {
      path: "../public/fonts/Pretendard/Pretendard-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "../public/fonts/Pretendard/Pretendard-Black.woff2",
      weight: "900",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head></head>
      <body
        className={` ${getPretendard.variable} ${getInter.variable}  antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
